### ISSUE TITLE
strict: true is not failing builds on missing frontmatter

### ISSUE THREAD

**Issue by redjax** [unmc-vcr/mkdocs-required-tags-plugin#1]
Love the idea for this plugin, thank you for building it!

I have added it to my project and added this section to my `plugins:`:

```
- required-frontmatter:
      enabled: true
      required-keys:
        - tags
        - a_test_tag
      ## Disable required frontmatter on specific files/paths
      exclude:
        ## All index.md files
        - index.md
        ## A path to a directory and file pattern
        # - example/path/*
      ## Fail build when page is missing frontmatter & strict: true
      strict: true
```

I added a test required-key, `a_test_tag`, which none of my pages have. When I run `mkdocs build`, the site builds without error. I believe this means I've configured it wrong, or something about my setup is causing this plugin not to work.

Let me know what information from me would be helpful for troubleshooting this, and I'm happy to be a guinea pig for any changes :)1
